[workspace]
members = [
    "runtime",
    "kernel",
    "libs/*",
    "exts/*",
]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = 1
incremental = false
debug-assertions = false
overflow-checks = false
